---
title: "CodingOutLoud3"
author: "Gwen Peterson"
format: html
#| warning : false
---
## Getting stuff

```{r}
#| message : false
library(tidyverse)
library(ggplot2)
library(ggforce)
```

## Task 1: Draw a Circle

```{r}
#Making the data
circle <- data_frame(
  x1 = 1,
  y1 = 1,
  r = 1
)

#plotting
ggplot() +
  geom_circle(
    aes(x0 = x1, y0 = y1, r = r),
    data = circle,
    fill = "black",
  ) +
  coord_fixed()
```

## Task 2: many circles in a line

```{r}
circles <- tibble(
  x1 = rep(1,9),
  x2 = seq(-0.2, 0.2, length.out = 9),
  y = seq(-1, 1, length.out = 9),
  x3 = sin(y) / 4,
  r1 = 1,
  r2 = (-(y^2) + 2) / 20
)
  
ggplot() +
  geom_circle(
    aes(x0 = x3, y0 = y, r = r2),
    data = circles,
    fill = "black",
  ) +
  coord_fixed() +
  theme_void()
```

## Task 3/4: Make a Pumpkin & Background

```{r}
#dataset w/ 9 rows (circles) and 3 variables (x & y coordinates of center, radius)
circles <- data_frame(
  id = 1:9,
  x1 = rep(1, 9),
  x2 = seq(-0.2, 0.2, length.out = 9),
  y = seq(-1, 1, length.out = 9),
  x_center = sin(y)/4,
  x_m1 = x_center - 0.25,
  x_m2 = x_center - 0.5,
  x_m3 = x_center - 0.75,
  x_p1 = x_center + 0.25,
  x_p2 = x_center + 0.5,
  x_p3 = x_center + 0.75,
  r1 = 0.05,
  r2 = (-(y^2) + 2) / 20
) |>
  mutate(
    x_m1 = if_else(y == max(y) | y == min(y), x_m1 + 0.1, x_m1),
    x_p1 = if_else(y == max(y) | y == min(y), x_p1 - 0.1, x_p1),
    x_m2 = if_else(y == min(y), x_m1 - 0.2, x_m1 - 0.25),
    r_m2 = (y + 2) / 30,
    y_m2 = if_else(y == min(y), y + 0.125, y),
    x_p2 = if_else(y == min(y), x_p1 + 0.2, x_p1 + 0.25),
    r_p2 = (y + 2) / 30,
    y_p2 = if_else(y == min(y), y + 0.125, y),
    x_m3 = x_m2 - (0.3 - y^2 / 8),
    r_m3 = (2 - y) / 30,
    y_m3 = y,
    x_p3 = x_p2 + (0.3 - y^2 / 8),
    r_p3 = (2 - y) / 30,
    y_p3 = y
)

ggplot() +
  #this is the yellow circle
  geom_circle(aes(x0 = 0, y0 = 0, r = 1.4), data = circles, fill = "#FFB100", color = "#FFB100") +
  #these are the black circles
  geom_circle(aes(x0 = x_center, y0 = y, r = r2), data = circles, fill = "black") +
  geom_circle(aes(x0 = x_m1, y0 = y, r = r1), data = circles, fill = "black") +
  geom_circle(aes(x0 = x_p1, y0 = y, r = r1), data = circles, fill = "black") +
  geom_circle(aes(x0 = x_m2, y0 = y_m2, r = r_m2), data = circles, fill = "black") +
  geom_circle(aes(x0 = x_p2, y0 = y_p2, r = r_p2), data = circles, fill = "black") +
  geom_circle(aes(x0 = x_m3, y0 = y_m3, r = r_m3), data = circles, fill = "black") +
  geom_circle(aes(x0 = x_p3, y0 = y_p3, r = r_p3), data = circles, fill = "black") +
  coord_fixed() +
#this makes the background
  theme_void() +
  theme(panel.background = element_rect(fill = "#FFDE00", color = "#FFDE00"))
```

## My added task: add a stem!

```{r}
ids <- factor(c("1.1", "2.1", "1.2", "2.2", "1.3", "2.3", "1.4"))

positions <- data.frame(
  id = ids,
  x_new = c(0, 2, 2.2, 2.75, 1.3, 0.6, 0.5) - 1.25,
  y_new = c(0.5, 0.75, 1.75, 2.8, 3.2, 3.25, 2.2)
)

#plot
ggplot() +
  geom_polygon(data = positions, aes(x = x_new, y = y_new), fill = "black") +
  coord_fixed()
```

Putting it together:

```{r}
ggplot() +
  #this is the yellow circle
  geom_circle(aes(x0 = 0, y0 = 0, r = 1.4), fill = "#FFB100", color = "#FFB100") +
  #these are the black circles
  geom_circle(aes(x0 = x_center, y0 = y, r = r2), data = circles, fill = "black") +
  geom_circle(aes(x0 = x_m1, y0 = y, r = r1), data = circles, fill = "black") +
  geom_circle(aes(x0 = x_p1, y0 = y, r = r1), data = circles, fill = "black") +
  geom_circle(aes(x0 = x_m2, y0 = y_m2, r = r_m2), data = circles, fill = "black") +
  geom_circle(aes(x0 = x_p2, y0 = y_p2, r = r_p2), data = circles, fill = "black") +
  geom_circle(aes(x0 = x_m3, y0 = y_m3, r = r_m3), data = circles, fill = "black") +
  geom_circle(aes(x0 = x_p3, y0 = y_p3, r = r_p3), data = circles, fill = "black") +
  coord_fixed() +
  geom_polygon(data = positions, aes(x = (x_new)/3, y = y_new/3 + 1.05), fill = "black") +
#this makes the background
  theme_void() +
  theme(panel.background = element_rect(fill = "#FFDE00", color = "#FFDE00"))
```

## Doing another cool thing: adding circles to the stem!

```{r}
yellow_circles <- tibble(
  id = 1:9,
  x = seq(-1.05, 0.65, length.out = 9) / 3,
  y = seq(0.7, 0.9, length.out = 9) / 3 + 1.05,
  r = (0.1 + (3*x)^2 / 25) / 4
)
  
ggplot() +
  geom_polygon(data = positions, aes(x = x_new/3, y = y_new/3 + 1.05), fill = "black") +
  geom_circle(aes(x0 = x, y0 = y, r = r), data = yellow_circles, fill = "#FFB100") +
  geom_circle(aes(x0 = x / 1.01 + 0.02, y0 = y + 0.25/3, r = r), data = yellow_circles, fill = "#FFB100") +
  geom_circle(aes(x0 = (x / 1.025) + 0.11/3, y0 = y + 0.5/3, r = r), data = yellow_circles, fill = "#FFB100") +
  geom_circle(aes(x0 = x / 1.035 + 0.175/3, y0 = y + 0.75/3, r = r), data = yellow_circles, fill = "#FFB100") +
  geom_circle(aes(x0 = x / 1.025 + 0.25/3, y0 = y + 1/3, r = r), data = yellow_circles, fill = "#FFB100") +
  geom_circle(aes(x0 = x + 0.35/3, y0 = y + 1.25/3, r = r), data = yellow_circles, fill = "#FFB100") +
  geom_circle(aes(x0 = x / 0.975 + 0.475/3, y0 = y + 0.5, r = r), data = yellow_circles, fill = "#FFB100") +
  geom_circle(aes(x0 = x / 0.925 + 0.55/3, y0 = y + 1.75/3, r = r), data = yellow_circles, fill = "#FFB100") +
  geom_circle(aes(x0 = x / 1.25 + 0.25/3, y0 = y / 1.1 + 0.775, r = r - 0.01), data = yellow_circles, fill = "#FFB100") +
  geom_circle(aes(x0 = x / 1.8 + 0.02/3, y0 = y / 1.35 + 1.055, r = r / 2), data = yellow_circles, fill = "#FFB100") +
  geom_circle(aes(x0 = x / 2.5 - 0.055, y0 = y / 1.75 + 1.325, r = r / 2), data = yellow_circles, fill = "#FFB100") +
  coord_fixed()
```

## The final product!

```{r}
ggplot() +
  #this is the yellow circle
  geom_circle(aes(x0 = 0, y0 = 0, r = 1.4), fill = "#FFB100", color = "#FFB100") +
  #these are the black circles
  geom_circle(aes(x0 = x_center, y0 = y, r = r2), data = circles, fill = "black") +
  geom_circle(aes(x0 = x_m1, y0 = y, r = r1), data = circles, fill = "black") +
  geom_circle(aes(x0 = x_p1, y0 = y, r = r1), data = circles, fill = "black") +
  geom_circle(aes(x0 = x_m2, y0 = y_m2, r = r_m2), data = circles, fill = "black") +
  geom_circle(aes(x0 = x_p2, y0 = y_p2, r = r_p2), data = circles, fill = "black") +
  geom_circle(aes(x0 = x_m3, y0 = y_m3, r = r_m3), data = circles, fill = "black") +
  geom_circle(aes(x0 = x_p3, y0 = y_p3, r = r_p3), data = circles, fill = "black") +
  coord_fixed() +
  #this is the stem
  geom_polygon(data = positions, aes(x = x_new/3, y = y_new/3 + 1.05), fill = "black") +
  #these are the circles on the stem
  geom_circle(aes(x0 = x, y0 = y, r = r), data = yellow_circles, fill = "#FFB100") +
  geom_circle(aes(x0 = x / 1.01 + 0.02, y0 = y + 0.25/3, r = r), 
              data = yellow_circles, fill = "#FFB100") +
  geom_circle(aes(x0 = (x / 1.025) + 0.11/3, y0 = y + 0.5/3, r = r), 
              data = yellow_circles, fill = "#FFB100") +
  geom_circle(aes(x0 = x / 1.035 + 0.175/3, y0 = y + 0.75/3, r = r), 
              data = yellow_circles, fill = "#FFB100") +
  geom_circle(aes(x0 = x / 1.025 + 0.25/3, y0 = y + 1/3, r = r), 
              data = yellow_circles, fill = "#FFB100") +
  geom_circle(aes(x0 = x + 0.35/3, y0 = y + 1.25/3, r = r), data = yellow_circles, 
              fill = "#FFB100") +
  geom_circle(aes(x0 = x / 0.975 + 0.475/3, y0 = y + 0.5, r = r), 
              data = yellow_circles, fill = "#FFB100") +
  geom_circle(aes(x0 = x / 0.925 + 0.55/3, y0 = y + 1.75/3, r = r), 
              data = yellow_circles, fill = "#FFB100") +
  geom_circle(aes(x0 = x / 1.25 + 0.25/3, y0 = y / 1.1 + 0.775, r = r - 0.01), 
              data = yellow_circles, fill = "#FFB100") +
  geom_circle(aes(x0 = x / 1.8 + 0.02/3, y0 = y / 1.35 + 1.055, r = r / 2), 
              data = yellow_circles, fill = "#FFB100") +
  geom_circle(aes(x0 = x / 2.5 - 0.055, y0 = y / 1.75 + 1.325, r = r / 2), 
              data = yellow_circles, fill = "#FFB100") +
#this makes the background
  theme_void() +
  theme(panel.background = element_rect(fill = "#FFDE00", color = "#FFDE00"))
```

